name: ✅ Test
on:
  push:

env:
  # Using Nx Cloud is safer
  NX_REJECT_UNKNOWN_LOCAL_CACHE: 0

jobs:
  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.ref_name }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install

      - name: Playwright browsers install
        run: pnpm playwright install --with-deps

      - name: Cache Nx
        uses: actions/cache@v3
        with:
          path: .nx/cache
          key: ${{ runner.os }}-nx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-nx

      - run: pnpm nx run-many --parallel=4 -t build,lint,test,test-ui

      # Skip Cypress Component tests on branches that don't have them
      # this avoids no specs error and polluting the code base
      # with some cypress test file from the beginning.
      - name: Has Cypress tests
        id: has-cypress-tests
        run: |
          if [ $(find apps libs -name '*.cy.ts' | wc -l) -gt 0 ]; then
            echo "has-cypress-tests=true" >> $GITHUB_OUTPUT
          else
            echo "has-cypress-tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Cypress component tests
        if: steps.has-cypress-tests.outputs.has-cypress-tests == 'true'
        run: pnpm nx run-many --parallel=4 -t component-test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 🎭 Playwright Report
          path: dist/.playwright
          retention-days: 7
